# 1.7 Introduction to Numpy

First import numpy:

In [1]:
import numpy as np

Check version:

In [2]:
np.__version__

'2.1.1'

## Create arrays

All zeros with size 3:

In [3]:
np.zeros(3)

array([0., 0., 0.])

All ones with size 10:

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Specify a size and number:

In [5]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Convert python list to array:

In [15]:
a = [1,2,4,1]

a_arr = np.array(a)

a_arr

array([1, 2, 4, 1])

Access third element (zero-indexed):

In [16]:
a_arr[2]

np.int64(4)

Change second element:

In [17]:
print(a_arr)

a_arr[1] = 999

print(a_arr)

[1 2 4 1]
[  1 999   4   1]


Create array based on range (0 to 10):

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

From 3 to 9:

In [19]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

Create array from 0 to 1 with 11 elements (i.e. in 10 steps):

In [20]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays

Create an array with 5 rows, 2 columns, filled with zeros:

In [21]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

We can also create a multi-dimensional array from a list of lists:

In [22]:
a = [[1,2,2], [2,14, 4]]

a_arr = np.array(a)

a_arr

array([[ 1,  2,  2],
       [ 2, 14,  4]])

Access first row, second column:

In [23]:
a_arr[0, 1]

np.int64(2)

Replace with 20:

In [32]:
a_arr[0, 1] = 20

a_arr

array([[ 1, 20,  2],
       [ 2, 14,  4]])

Get first row and second row:

In [33]:
a_arr[0]

[1, 2, 2]

In [36]:
a_arr[1]

array([ 2, 14,  4])

Change second row to something else:

In [37]:
a_arr[1] = [2,1,1]

In [38]:
a_arr

array([[ 1, 20,  2],
       [ 2,  1,  1]])

Same for column

In [39]:
a_arr[:, 0]

array([1, 2])

In [40]:
a_arr[:, 0] = [10, 20]

In [41]:
a_arr

array([[10, 20,  2],
       [20,  1,  1]])

Randomly generated array with 5 rows and 2 columns:

In [60]:
np.random.seed(2)          # seed to make results reproducible
np.random.rand(5, 2)    # this is standard uniform distribution between 0 and 1

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

Make it between 0 and 100

In [61]:
100 * np.random.rand(5, 2)

array([[62.11338328, 52.91420943],
       [13.45799453, 51.35781213],
       [18.44398656, 78.53351478],
       [85.39752926, 49.42368374],
       [84.65614854,  7.9645477 ]])

Now from standard normal distribution:

In [58]:
np.random.randn(5, 2)

array([[ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737],
       [-0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761]])

Random integers between 0 and 100:

In [62]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[68, 46],
       [70, 95],
       [83, 31],
       [66, 80],
       [52, 76]])

## Element-wise operations

Addition:

In [63]:
a = np.arange(5)

In [64]:
a + 10

array([10, 11, 12, 13, 14])

Multiplication:

In [65]:
a * 2

array([0, 2, 4, 6, 8])

Division:

In [66]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

It can be chained:

In [67]:
( (a + 10) / 2 ) * 4

array([20., 22., 24., 26., 28.])

You can add arrays:

In [72]:
(a + 3 * a ) / (a + 1)

array([0.        , 2.        , 2.66666667, 3.        , 3.2       ])

## Comparison operations

In [74]:
a > (10*a)

array([False, False, False, False, False])

In [75]:
a == a

array([ True,  True,  True,  True,  True])

In [76]:
a < 2

array([ True,  True, False, False, False])

Filter array on elements larger than 2:

In [77]:
a[a > 2]

array([3, 4])

## Summary operations

In [79]:
a.min()

np.int64(0)

In [80]:
a.sum()

np.int64(10)

In [81]:
a.max()

np.int64(4)

In [82]:
a.mean()

np.float64(2.0)

In [83]:
a.std()

np.float64(1.4142135623730951)