# Linear Algebra Refresher

## Vector Operations

We have vectors $ \mathbf{u} $ and $ \mathbf{v} $ below:

$$ \mathbf{u} = \begin{bmatrix} 2 \\ 4 \\ 5 \\ 6 \end{bmatrix}, \mathbf{v} = \begin{bmatrix} 1 \\ 0 \\ 0 \\ 2 \end{bmatrix} $$

### Multiplication with a scalar

We can multiply a vector by any scalar number, e.g.:

$$ 2 \mathbf{u} = 2 \begin{bmatrix} 2 \\ 4 \\ 5 \\ 6 \end{bmatrix} = \begin{bmatrix} 4 \\ 8 \\ 10 \\ 12 \end{bmatrix}$$

### Addition of a vector and a scalar

$$ \mathbf{u} + 2 = \begin{bmatrix} 2 \\ 4 \\ 5 \\ 6 \end{bmatrix} + 2 = \begin{bmatrix} 4 \\ 6 \\ 7 \\ 8 \end{bmatrix}$$

### Addition of vectors

We can add vectors:

$$ \mathbf{u} + \mathbf{v} = \begin{bmatrix} 2 \\ 4 \\ 5 \\ 6 \end{bmatrix} + \begin{bmatrix} 1 \\ 0 \\ 0 \\ 2 \end{bmatrix} = \begin{bmatrix} 3 \\ 4 \\ 5 \\ 8 \end{bmatrix}$$


### Vector-vector multiplication (dot product or inner product)

$$
\mathbf{u}^T \mathbf{v} = \langle \mathbf{u}, \mathbf{v} \rangle = \sum_{i=1}^{n} u_i v_i = \begin{bmatrix} 2 & 4 & 5 & 6 \end{bmatrix} \begin{bmatrix} 1 \\ 0 \\ 0 \\ 2 \end{bmatrix} = 2 \cdot 1 + 4 \cdot 0 + 5 \cdot 0 + 6 \cdot 2 = 14
$$

The first three expressions are different notations for the dot product (or inner product) of two vectors:
1. $ \mathbf{u}^T \mathbf{v} $: Matrix multiplication of the transpose of $ \mathbf{u} $ and $ \mathbf{v} $, which is the standard matrix form of the dot product.
2. $ \langle \mathbf{u}, \mathbf{v} \rangle $: Angle bracket notation commonly used in functional analysis and physics for the inner product.
3. $ \sum_{i=1}^{n} u_i v_i $: Explicit summation over the components, representing the dot product as the sum of element-wise products (also known as the Einstein notation).



### Matrix-vector multiplication

## Linear Algebra in Numpy

In Numpy we can do this as follows:

In [74]:
import numpy as np


u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [75]:
u

array([2, 4, 5, 6])

In [76]:
v

array([1, 0, 0, 2])

Note that although $\mathbf{u}$ and $\mathbf{v}$ are rendered as row vectors $( 1 \times n )$, if we look at their shapes, we can see that the second dimension is unspecified:

In [25]:
u.shape

(4,)

We could explicitly turn this into $(1 \times n)$ (row vector) as follows:

In [30]:
u_row = u.reshape(-1, 4)
u_row

array([[2, 4, 5, 6]])

Or into an column vector $( m \times 1 )$:

In [45]:
u_col = u.reshape(4, -1)
u_col

array([[2],
       [4],
       [5],
       [6]])

The `.reshape()` function takes an array and reshapes it into the dimensions you want (provided that the number of elements of the resulting array match that of the original). The `-1` indicates that you want Numpy to figure out how many elements of that dimensions are needed. Numpy will by default read the elements from left to right, top to bottom, and populate the dimensions of the reshaped array. 

But for vector algebra, we can leave $\mathbf{u}$ and $\mathbf{v}$ as is (no need to use `.reshape` to explicitly turn them into a row or column vectors).

Multiplication with a scalar:

In [50]:
u * 2

array([ 4,  8, 10, 12])

Adding a vector and a scalar:

In [52]:
u + 2

array([4, 6, 7, 8])

Adding two vectors:

In [51]:
u + v

array([3, 4, 5, 8])

Element-wise multiplication of two vectors:

In [53]:
u * v

array([ 2,  0,  0, 12])

Dot (inner) product (3 ways of doing it):

In [54]:
np.dot(u, v)

np.int64(14)

In [66]:
u.dot(v)

np.int64(14)

In [55]:
u @ v

np.int64(14)

Here's a code implementation of the dot product (inefficient implementation, just for educational purposes):

In [73]:
def vector_vector_multiplication(u, v):
    
    # first check that shapes are compatible:
    assert u.shape == v.shape

    # get number of elements
    n = u.shape[0]

    result = 0

    # loop over elements and add their product to the result
    for i in range(n):
        result += u[i] * v[i]
    return result

vector_vector_multiplication(u, v)

np.int64(14)