# 1.8 Linear Algebra Refresher

## Vector Operations

We have vectors $ \mathbf{u} $ and $ \mathbf{v} $ below:

$$ \mathbf{u} = \begin{bmatrix} 2 \\ 4 \\ 5 \\ 6 \end{bmatrix}, \mathbf{v} = \begin{bmatrix} 1 \\ 0 \\ 0 \\ 2 \end{bmatrix} $$

### Multiplication with a scalar

We can multiply a vector by any scalar number, e.g.:

$$ 2 \mathbf{u} = 2 \begin{bmatrix} 2 \\ 4 \\ 5 \\ 6 \end{bmatrix} = \begin{bmatrix} 4 \\ 8 \\ 10 \\ 12 \end{bmatrix}$$

### Addition of a vector and a scalar

$$ \mathbf{u} + 2 = \begin{bmatrix} 2 \\ 4 \\ 5 \\ 6 \end{bmatrix} + 2 = \begin{bmatrix} 4 \\ 6 \\ 7 \\ 8 \end{bmatrix}$$

### Addition of vectors

We can add vectors:

$$ \mathbf{u} + \mathbf{v} = \begin{bmatrix} 2 \\ 4 \\ 5 \\ 6 \end{bmatrix} + \begin{bmatrix} 1 \\ 0 \\ 0 \\ 2 \end{bmatrix} = \begin{bmatrix} 3 \\ 4 \\ 5 \\ 8 \end{bmatrix}$$

### Vector-vector multiplication (dot product or inner product)

$$
\mathbf{u}^T \mathbf{v} = \langle \mathbf{u}, \mathbf{v} \rangle = \sum_{i=1}^{n} u_i v_i = \begin{bmatrix} 2 & 4 & 5 & 6 \end{bmatrix} \begin{bmatrix} 1 \\ 0 \\ 0 \\ 2 \end{bmatrix} = 2 \cdot 1 + 4 \cdot 0 + 5 \cdot 0 + 6 \cdot 2 = 14
$$

The first three expressions are different notations for the dot product (or inner product) of two vectors:
1. $ \mathbf{u}^T \mathbf{v} $: Matrix multiplication of the transpose of $ \mathbf{u} $ and $ \mathbf{v} $, which is the standard matrix form of the dot product.
2. $ \langle \mathbf{u}, \mathbf{v} \rangle $: Angle bracket notation commonly used in functional analysis and physics for the inner product.
3. $ \sum_{i=1}^{n} u_i v_i $: Explicit summation over the components, representing the dot product as the sum of element-wise products (also known as the Einstein notation).



### Matrix-vector multiplication

We have matrix $\mathbf{U}$ and vector $\mathbf{v}$ as below.

$$
\mathbf{U}=\begin{bmatrix} 2 & 4 & 5 & 5 \\ 1 & 2 & 1 & 2 \\ 3 & 1 & 2 & 1 \end{bmatrix}, \mathbf{v}=\begin{bmatrix} 1 \\ 0.5 \\ 2 \\ 1 \end{bmatrix}
$$

We want to multiply:
$$
\mathbf{U} \cdot \mathbf{v}
$$

The dimension of $\mathbf{U}$ is $3 \times 4$ and of $\mathbf{v}$ is $4 \times 1$. Therefore the matrix-vector product should be a vector with dimensions $3 \times 1$.

For each row of the matrix $\mathbf{U}$, we calculate the dot product with $\mathbf{v}$. Let $\mathbf{u}_i$ represent the i-th row of $\mathbf{U}$, where:
$$
\mathbf{u}_0=\begin{bmatrix} 2 \\ 4 \\ 5 \\ 5 \end{bmatrix}, 
\mathbf{u}_1=\begin{bmatrix} 1 \\ 2 \\ 1 \\ 2 \end{bmatrix}, 
\mathbf{u}_2=\begin{bmatrix} 3 \\ 1 \\ 2 \\ 1 \end{bmatrix}
$$

The result of the multiplication is the following vector, where each entry is the dot product of the corresponding row of $\mathbf{U}$ with $\mathbf{v}$:
$$
\mathbf{U} \mathbf{v} = \begin{bmatrix} \mathbf{u}_0^T \mathbf{v} \\ \mathbf{u}_1^T \mathbf{v} \\ \mathbf{u}_2^T \mathbf{v} \end{bmatrix}
$$

### Matrix-matrix multiplication

Consider matrices:

$$
\mathbf{U}=\begin{bmatrix} 2 & 4 & 5 & 5 \\ 1 & 2 & 1 & 2 \\ 3 & 1 & 2 & 1 \end{bmatrix}, 
\mathbf{V}=\begin{bmatrix} 1 & 1 & 2 \\ 0 & 0.5 & 1 \\ 0 & 2 & 1 \\ 2 & 1 & 0\end{bmatrix} 
$$

We want to compute $\mathbf{U} \mathbf{V}$. Let's represent $\mathbf{V}$ as: 

$$\begin{bmatrix} \mathbf{v}_0 & \mathbf{v}_1 & \mathbf{v}_2 \end{bmatrix}$$

Then the matrix-multiplication becomes:
$$
\mathbf{U} \mathbf{V} = \begin{bmatrix} \mathbf{U} \mathbf{v}_0 & \mathbf{U} \mathbf{v}_1 & \mathbf{U} \mathbf{v}_2 \end{bmatrix}
$$

### Identity Matrix

Identity matrix has ones on the diagonal. Here's an example of a $4 \times 4$ identity matrix:

$$
\mathbf{I} = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}
$$

If the identity matrix is multiplied with any matrix, the product is equal to that matrix:
$$
\mathbf{U} \mathbf{I} = \mathbf{I} \mathbf{U} = \mathbf{U}
$$

### Matrix inverse

Let's say we have a matrix $\mathbf{A}$. Its inverse $\mathbf{A}^{-1}$ is defined such that, when multiplied with $\mathbf{A}$, the product is the identity matrix $\mathbf{I}$:

$$
\mathbf{A}^{-1} \mathbf{A} = \mathbf{I}
$$
$$
\mathbf{A} \mathbf{A}^{-1} = \mathbf{I}
$$

The inverse only exists for square matrices.

## Linear Algebra in Numpy

### Defining vectors in Numpy

In Numpy we can do this as follows:

In [5]:
import numpy as np


u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [6]:
u

array([2, 4, 5, 6])

In [7]:
v

array([1, 0, 0, 2])

### `.shape` and `.reshape()`

Note that although $\mathbf{u}$ and $\mathbf{v}$ are rendered as row vectors $( 1 \times n )$, if we look at their shapes, we can see that the second dimension is unspecified:

In [8]:
u.shape

(4,)

We could explicitly turn this into $(1 \times n)$ (row vector) as follows:

In [9]:
u_row = u.reshape(-1, 4)
u_row

array([[2, 4, 5, 6]])

Or into an column vector $( m \times 1 )$:

In [10]:
u_col = u.reshape(4, -1)
u_col

array([[2],
       [4],
       [5],
       [6]])

The `.reshape()` function takes an array and reshapes it into the dimensions you want (provided that the number of elements of the resulting array match that of the original). The `-1` indicates that you want Numpy to figure out how many elements of that dimensions are needed. Numpy will by default read the elements from left to right, top to bottom, and populate the dimensions of the reshaped array. 

But for vector algebra, we can leave $\mathbf{u}$ and $\mathbf{v}$ as is (no need to use `.reshape` to explicitly turn them into a row or column vectors).

### Multiplication with a scalar

In [11]:
u * 2

array([ 4,  8, 10, 12])

### Adding a vector and a scalar

In [12]:
u + 2

array([4, 6, 7, 8])

### Adding two vectors

In [13]:
u + v

array([3, 4, 5, 8])

### Element-wise multiplication of two vectors

In [14]:
u * v

array([ 2,  0,  0, 12])

### Dot (inner) product (3 ways of doing it)

In [15]:
np.dot(u, v)

np.int64(14)

In [16]:
u.dot(v)

np.int64(14)

In [17]:
u @ v

np.int64(14)

Here's a code implementation of the dot product (inefficient implementation, just for educational purposes):

In [18]:
def vector_vector_multiplication(u, v):
    
    # first check that shapes are compatible:
    assert u.shape == v.shape

    # get number of elements
    n = u.shape[0]

    result = 0

    # loop over elements and add their product to the result
    for i in range(n):
        result += u[i] * v[i]
    return result

vector_vector_multiplication(u, v)

np.int64(14)

### Matrix-vector multiplication

In [19]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [70]:
U @ v  # Preferred

array([14,  5,  5])

In [26]:
U.dot(v)

array([14,  5,  5])

In [27]:
np.dot(U, v)

array([14,  5,  5])

In [25]:
np.matmul(U, v)

array([14,  5,  5])

Code implementation of matrix-vector multiplication (just for educational purposes):

In [64]:
def matrix_vector_multiplication(U, v):
    
    assert (U.shape[1] == v.shape[0]) and len(v.shape) == 1
    

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

matrix_vector_multiplication(U, v)


array([14.,  5.,  5.])

### Matrix-matrix multiplication

In [65]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [71]:
U @ V  # Preferred

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [67]:
np.dot(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [68]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [69]:
np.matmul(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [77]:
def matrix_matrix_multiplication(U, V):
    
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        result[:, i] = matrix_vector_multiplication(U, V[:, i])
    return result

matrix_matrix_multiplication(U, V)


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix

In [78]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [80]:
I = np.eye(3)

In [87]:
I @ U == U

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
I = np.eye(4)

In [89]:
U @ I == U

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Matrix inverse

Let's take first 3 rows of V (to have a square matrix):

In [92]:
V_s = V[:3, :]

In [95]:
V_s_inv = np.linalg.inv(V_s)

In [99]:
V_s @ V_s_inv == np.eye(3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [100]:
V_s_inv @ V_s == np.eye(3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])